### ISSUE TITLE
SAF授权问题

### ISSUE THREAD

**Issue by angxb-ANGXB** [lalakii/android_airplane_mode#1]
大佬，安卓14设备上拉起SAF授权Android/data/【packname】提示无法使用这个文件夹，不知能否通过放射方法实现授权
![Screenshot_20240314_200155_com android documentsui_edit_429617043641425](https://github.com/lalakii/android_airplane_mode/assets/60745027/f1fa5c39-f40a-4541-8e70-6a4c8cd4bfba)

![Screenshot_20240314_200153_com android documentsui_edit_429574182055139](https://github.com/lalakii/android_airplane_mode/assets/60745027/c23c5a8d-b443-4fe9-88f9-c967a43a3b00)

**Comment by lalakii** [comment]
没看懂你需要做什么，如果只是需要读取里面的文件，有shizuku应该是够了。

这里不要提无关项目的问题，去StackOverflow提问，并且一定要懂得将问题描述清楚。
